### ISSUE TITLE
[C++]  默认模板下的C++库找不到

### ISSUE THREAD

**Issue by sonderlau** [supperchong/algorithm#12]
![图片](https://user-images.githubusercontent.com/12829325/124378191-ba39c580-dce2-11eb-966f-116fe9872382.png)
打开问题后 显示的是 `#include "algm/algm.h"`
也许应该是 `#include "algorithm"` ?

**Comment by supperchong** [comment]
@sonderlau 打开文件夹 默认是 `$HOME/.alg`

**Comment by sonderlau** [comment]
我在`c_cpp_properties.json` 中配置了下`"includePath"` 将`.$HOME/.alg/cn/C++/**` 添加进去就解决了
Thanks.
