### ISSUE TITLE
python3 无法调试二维数组参数

### ISSUE THREAD

**Issue by Tephen** [supperchong/algorithm#13]
对37题数独test时弹出paramType error，显示
parse params err: Error: paramType character[][] not support

37题模版为
class Solution:
    def solveSudoku(self, board: List[List[str]]) -> None:

似乎不支持传入board此类参数进行调试

**Comment by supperchong** [comment]
感谢反馈，已修复

**Comment by supperchong** [comment]
@Tephen 已发布[v0.0.5](https://marketplace.visualstudio.com/items?itemName=supperchong.algorithm&ssr=false#version-history)
