### ISSUE TITLE
python 调试后台吃cpu

### ISSUE THREAD

**Issue by Tephen** [supperchong/algorithm#14]
本地有死循环的代码多进行了几次test后似乎一直在占用系统资源，后续代码改正后test通过，但是之前的test进程似乎还在继续运行吃资源，是否可以设置一段时间后自动kill掉调试进程？昨天晚上没有退出vscode电脑休眠，到早上电脑发热严重且电量极低
<img width="473" alt="截屏2021-07-06 上午9 32 46" src="https://user-images.githubusercontent.com/22749065/124529655-9fc82f00-de3d-11eb-85d4-d91f7a0cd85f.png">
<img width="729" alt="截屏2021-07-06 上午9 33 35" src="https://user-images.githubusercontent.com/22749065/124529670-a6ef3d00-de3d-11eb-8e31-2ff22bc27a14.png">

**Comment by Tephen** [comment]
强制退出vscode后test进程仍然存在且仍在继续吃cpu

**Comment by Tephen** [comment]
感谢修复

**Comment by supperchong** [comment]
@Tephen 感谢反馈 已发布[v0.0.6](https://marketplace.visualstudio.com/items?itemName=supperchong.algorithm&ssr=false#version-history)
