### ISSUE TITLE
打开Tag菜单时报错 ”ID 为 排序 的元素已被注册“ 

### ISSUE THREAD

**Issue by ctravel** [supperchong/algorithm#23]
打开Tag菜单时报如下错误，并且Tag展开为空；

![image](https://user-images.githubusercontent.com/59652630/136654319-9521b320-3db1-4599-bf7f-2572024868f2.png)

**Comment by supperchong** [comment]
fixed  https://github.com/supperchong/algorithm/commit/907544a6677198188568b682445316f7d0cb6519
已发布v0.0.7
