### ISSUE TITLE
Python3 DEBUG和test无法使用

### ISSUE THREAD

**Issue by Eliza612** [supperchong/algorithm#25]
剑指的题目 python3环境
Debug在output中显示 “please select the test case”
test则短暂提示“wait test”然后就没有output了
不知道可能是哪里的问题 期待您的回复！

**Comment by Eliza612** [comment]
卸载重装之后依然是wait test
output部分是安装时候的
```
installing algm...
install algm success
```
以及debug也不work QAQ

**Comment by supperchong** [comment]
@Eliza612 不好意思才看到，解决了吗

**Comment by Eliza612** [comment]
@supperchong 没问题没问题 已经解决！太好用啦，真的感谢！
